FROM node:14-alpine

WORKDIR /app

# Command is appended after the entry point
ENTRYPOINT ["npm"]

# docker build -t node node-util .
# docker run -it -v /Users/arthur/Dev/docker-kubernetes-practice/utility-container:/app  node-util npm init

# docker run -it -v /Users/arthur/Dev/docker-kubernetes-practice/utility-container:/app mynpm init
# docker run -it -v /Users/arthur/Dev/docker-kubernetes-practice/utility-container:/app mynpm install express

